version: "3.8"

services:
  # image project
  app-hermes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-hermes
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - hermes-network

  # nginx
  nginx-hermes:
    container_name: nginx-hermes
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - hermes-network

  # db mysql
  mysql-hermes:
    container_name: mysql-hermes
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - "3388:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - hermes-network

volumes:
  mariadbdata:
    driver: local

networks:
  hermes-network:
    driver: bridge
